<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXhvpuz9\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXhvpuz9/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXhvpuz9.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXhvpuz9\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXhvpuz9\appProdProjectContainer([
    'container.build_hash' => 'Xhvpuz9',
    'container.build_id' => 'f47b81d3',
    'container.build_time' => 1575912515,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXhvpuz9');
